[font]
size = 12.0

[font.normal]
family = "Iosevka"
style = "Extended"

[window]
opacity = 0.8

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

# Twilight theme colors
[colors.primary]
background = "#141414"
foreground = "#FEFFD3"

[colors.normal]
black   = "#141414"
red     = "#C06C43"
green   = "#AFB979"
yellow  = "#C2A86C"
blue    = "#444649"
magenta = "#B4BE7B"
cyan    = "#778284"
white   = "#FEFFD3"

[colors.bright]
black   = "#303030"
red     = "#D27B52"
green   = "#BFC888"
yellow  = "#D1B77B"
blue    = "#555759"
magenta = "#C3CD8A"
cyan    = "#889193"
white   = "#FEFFD3"

[colors.selection]
background = "#303030"
text = "#FEFFD3"